name: update-flake-lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@d96678350ffd6a456235832eb11e1c491589b7bb # v3
      - name: Enable FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@77c6bddd7d747943530aaa578c57f233ee5d920e # main
      - name: Update flake.lock
        uses: ./.
        with:
          _internal-strict-mode: true
